version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fantasy_db
      POSTGRES_USER: fantasyuser
      POSTGRES_PASSWORD: localpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
